name: turfmapp

services:
  # Frontend (React Client)
  turfmapp-client:
    build:
      context: ./client
      dockerfile: ../config/development/Dockerfile.client
    container_name: turfmapp-client
    restart: on-failure
    volumes:
      - ./client:/app/client
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_BASE_URL=http://localhost:9000
      - REACT_APP_ELEVENLABS_AGENT_ID=agent_6601khmmm2r9ed0rdnjhr46a34mp
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app/client
    command: npm start
    networks:
      - shared_network
    depends_on:
      - turfmapp-server

  # Backend (API Server)
  turfmapp-server:
    build:
      context: ./server
      dockerfile: ../config/development/Dockerfile.server
    container_name: turfmapp-server
    command: sh -c "node db/init.js && node app.js --prod"
    restart: on-failure
    volumes:
      - ./server:/app
      - /app/node_modules
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 9000:1337

    environment:
      - BASE_URL=http://localhost:9000
      - DATABASE_URL=postgresql://postgres.pwxhgvuyaxgavommtqpr:Tzt0bkistz7Hi2af@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
      - SECRET_KEY=NL6mKqSUrjwmvN2ew0xlEHysFft6R2pQNPTduKJXhxuJ9TfMKtcQ2oBsPNXu

      - TRUST_PROXY=1
      - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false
      # - TOKEN_EXPIRES_IN=365 # In days

      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>
      - PGOPTIONS=-c search_path=project_management_tool,public
      - NODE_TLS_REJECT_UNAUTHORIZED=0

      # SSL is now enabled above for Supabase connection

      - DEFAULT_ADMIN_EMAIL=admin@turfmapp.com
      - DEFAULT_ADMIN_PASSWORD=admin123
      - DEFAULT_ADMIN_NAME=Admin User
      - DEFAULT_ADMIN_USERNAME=admin
      # - SHOW_DETAILED_AUTH_ERRORS=false #Â Set to true to show more detailed authentication error messages. It should not be enabled without a rate limiter for security reasons.
      # - ALLOW_ALL_TO_CREATE_PROJECTS=true

      - S3_ENDPOINT=https://769c64a7e39c6ea5f51513b8e2ed9c5b.r2.cloudflarestorage.com
      - S3_REGION=auto
      - S3_ACCESS_KEY_ID=9f3ce3b3548bead7a9ce8f7da8f3a71c
      - S3_SECRET_ACCESS_KEY=8a144d9d6b3b79bfb107693c35db5d861842f37b8c968f39f817403850341ad4
      - S3_BUCKET=project-management-tool
      - S3_FORCE_PATH_STYLE=true
      # - OIDC_ISSUER=
      # - OIDC_CLIENT_ID=
      # - OIDC_CLIENT_SECRET=
      # - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=
      # - OIDC_USERINFO_SIGNED_RESPONSE_ALG=
      # - OIDC_SCOPES=openid email profile
      # - OIDC_RESPONSE_MODE=fragment
      # - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_CLAIMS_SOURCE=userinfo
      # - OIDC_EMAIL_ATTRIBUTE=email
      # - OIDC_NAME_ATTRIBUTE=name
      # - OIDC_USERNAME_ATTRIBUTE=preferred_username
      # - OIDC_ROLES_ATTRIBUTE=groups
      # - OIDC_IGNORE_USERNAME=true
      # - OIDC_IGNORE_ROLES=true
      # - OIDC_ENFORCED=true

      # Email Notifications (https://nodemailer.com/smtp/)
      # - SMTP_HOST=
      # - SMTP_PORT=587
      # - SMTP_NAME=
      # - SMTP_SECURE=true
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_FROM="Demo Demo" <demo@demo.demo>
      # - SMTP_TLS_REJECT_UNAUTHORIZED=false

      # Optional fields: accessToken, events, excludedEvents
      # - |
      #   WEBHOOKS=[{
      #     "url": "http://localhost:3001",
      #     "accessToken": "notaccesstoken",
      #     "events": ["cardCreate", "cardUpdate", "cardDelete"],
      #     "excludedEvents": ["notificationCreate", "notificationUpdate"]
      #   }]

      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=

      # - GOOGLE_CHAT_WEBHOOK_URL=

      # - TELEGRAM_BOT_TOKEN=
      # - TELEGRAM_CHAT_ID=
      # - TELEGRAM_THREAD_ID=
    networks:
      - shared_network

volumes:
  user-avatars:
  project-background-images:
  attachments:


networks:
  shared_network:
    external: true
